# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupil', '0025_auto_20160609_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='hint1',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions',
            name='hint2',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions',
            name='hint3',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions',
            name='hint4',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option1',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option2',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option3',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option4',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions1',
            name='hint1',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions1',
            name='hint2',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions1',
            name='hint3',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions1',
            name='hint4',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions1',
            name='option1',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions1',
            name='option2',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions1',
            name='option3',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions1',
            name='option4',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions2',
            name='hint1',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions2',
            name='hint2',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions2',
            name='hint3',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions2',
            name='hint4',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions2',
            name='option1',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions2',
            name='option2',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions2',
            name='option3',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions2',
            name='option4',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions3',
            name='hint1',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions3',
            name='hint2',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions3',
            name='hint3',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions3',
            name='hint4',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions3',
            name='option1',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions3',
            name='option2',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions3',
            name='option3',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions3',
            name='option4',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions4',
            name='hint1',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions4',
            name='hint2',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions4',
            name='hint3',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions4',
            name='hint4',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions4',
            name='option1',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions4',
            name='option2',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions4',
            name='option3',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions4',
            name='option4',
            field=models.CharField(max_length=60),
        ),
    ]
